[tool.poetry]
name = "pinecone-datasets"
version = "0.1.1"
description = "Pinecone Datasets lets you easily load datasets into your Pinecone index."
authors = ["Pinecone"]
maintainers = [
    "Roy Miara <miararoy@gmail.com>",
]
readme = "README.md"


[tool.poetry.dependencies]
python = "^3.7"
polars = "^0.16.4"
pyarrow = "^11.0.0"
fsspec = "^2023.1.0"
gcsfs = "^2023.1.0"
s3fs = "^2023.1.0"
pydantic = "^1.10.5"
protobuf = ">=3.19.3,<3.20.0"
pandas = "^1.5.3"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.21.1"
pinecone-client = {git = "git@github.com:pinecone-io/pinecone-python-client.git", rev = "add_dict_support", extras=["grpc"]}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
