[tool.poetry]
name = "datasets"
version = "0.1.0"
description = ""
authors = ["Roy Miara <miararoy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
polars = "^0.16.4"
pyarrow = "^11.0.0"
fsspec = "^2023.1.0"
gcsfs = "^2023.1.0"
s3fs = "^2023.1.0"
pinecone-client = "^2.1.0"
pydantic = "^1.10.5"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
ipykernel = "^6.21.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
